# Generated by Django 2.1.1 on 2018-11-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='zan',
            field=models.IntegerField(default=0),
        ),
    ]
